# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  platform :ios, '9.0'
target 'MusicTrendsAndroid' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MusicTrendsAndroid
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  target 'MusicTrendsAndroidTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MusicTrendsAndroid-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MusicTrendsAndroid-tvOS

  target 'MusicTrendsAndroid-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
