# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  platform :ios, '9.0'
target 'MusicTrendsAndroid' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicTrendsAndroid

  

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  target 'MusicTrendsAndroidTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MusicTrendsAndroid-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicTrendsAndroid-tvOS

  target 'MusicTrendsAndroid-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
