# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  platform :ios, '9.0'
target 'AudioBuzz' do

  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTPushNotification',
    'RCTCameraRoll',
    'RCTSettings',
    'RCTBlob',
    'RCTGeolocation',
    'DevSupport'
  ]

  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AudioBuzz
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'AudioBuzzTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AudioBuzz-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AudioBuzz-tvOS

  target 'AudioBuzz-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
